added anchor for table of contents
slub/slub_zotero pull request #5
Opened 2021-09-01 15:11 UTC by tobiaskresse

2021-10-01 11:04 UTC, albig requested changes
Please remove debug output

2021-10-01 11:04 UTC, albig commented on Resources/Private/Templates/Bibliografie/List.html
> +    <f:debug>{settings}</f:debug>
```suggestion
```

2021-10-01 13:23 UTC, ByteParty requested changes

2021-10-01 13:23 UTC, ByteParty commented on Resources/Private/Templates/Bibliografie/List.html
> +      <f:debug>{_all}</f:debug>
please remove the debug code.

2021-10-01 13:23 UTC, ByteParty commented on Resources/Private/Templates/Bibliografie/List.html
> +          <h3 class="tx-slub-zotero-collection-title" id="c{collection.data.title}{collectionIterator.cycle}">{collection.data.title}</h3>
Please do not use a title as id. Use only the iterator or a zotero id.

2021-10-29 14:25 UTC, albig approved these changes

2021-10-29 14:25 UTC, merged